name: 'Astro deploy'
description: 'Deploy astro to S3'
inputs:
  bucket:
    description: 'Bucket name'
    required: true
  config:
    description: 'aws config'
    required: true
  cred: 
    description: 'aws cred'
    required: true
runs:
  using: "composite"
  steps:
      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 22
          check-latest: true

      - shell: bash
        name: Install dependencies 👨🏻‍💻
        run: npm install

      - shell: bash
        name: Run build 🔨
        run: npm run build

      - shell: bash
        name: Setup S3 🔐
        env:
          AWS_CONFIG: ${{ inputs.config }}
          AWS_CRED: ${{ inputs.cred }}
        run: |
          mkdir ~/.aws
          touch ~/.aws/config
          touch ~/.aws/credentials
          echo "$AWS_CONFIG" >> ~/.aws/config
          echo "$AWS_CRED" >> ~/.aws/credentials

      - shell: bash
        name: Sync files to S3 bucket 🚀
        env:
            BUCKET: ${{ inputs.bucket }}
        run: |
          aws s3 sync dist/ s3://$BUCKET/